#ifndef CBEFF_DEVICE_IDENTIFIERS_H_INCLUDED
#define CBEFF_DEVICE_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

#define CBEFF_DI_VENDOR_UNKNOWN_PRODUCT_UNKNOWN 0x0001

N_DECLARE_STATIC_OBJECT_TYPE(CbeffDeviceIdentifiers)

#ifdef N_CPP
}
#endif

#endif // !CBEFF_DEVICE_IDENTIFIERS_H_INCLUDED
