#ifndef CBEFF_SB_FORMAT_IDENTIFIERS_H_INCLUDED
#define CBEFF_SB_FORMAT_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

N_DECLARE_STATIC_OBJECT_TYPE(CbeffSBFormatIdentifiers)

#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER    0x0001
#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER    0x0002
#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER    0x0003
#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER_SO 0x0004
#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER_SO 0x0005
#define CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER_SO 0x0006

#ifdef N_CPP
}
#endif

#endif // !CBEFF_SB_FORMAT_IDENTIFIERS_H_INCLUDED
