#ifndef CBEFF_PATRON_FORMAT_IDENTIFIERS_HPP_INCLUDED
#define CBEFF_PATRON_FORMAT_IDENTIFIERS_HPP_INCLUDED

#include <Core/NTypes.hpp>
namespace Neurotec { namespace Biometrics { namespace Standards
{
#include <Biometrics/Standards/CbeffPatronFormatIdentifiers.h>
}}}

namespace Neurotec { namespace Biometrics { namespace Standards
{

#undef CBEFF_PFI_NIST_D
#undef CBEFF_PFI_NIST_E

#undef CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_A
#undef CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_B
#undef CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_C
#undef CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_D

#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BIT_ORIENTED
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BYTE_ORIENTED
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_PRESENCE_BYTE_ORIENTED
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIT_ORIENTED
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_TLV_ENCODED
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_COMPLEX
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_XML
#undef CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIOAPI

const NUShort CBEFF_PFI_NIST_D = 0x0001;
const NUShort CBEFF_PFI_NIST_E = 0x0002;

const NUShort CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_A = 0x0001;
const NUShort CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_B = 0x0002;
const NUShort CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_C = 0x0003;
const NUShort CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_D = 0x0004;

const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BIT_ORIENTED = 0x0001;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BYTE_ORIENTED = 0x0002;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_PRESENCE_BYTE_ORIENTED = 0x0003;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIT_ORIENTED = 0x0004;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_TLV_ENCODED = 0x0005;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_COMPLEX = 0x0006;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_XML = 0x0007;
const NUShort CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIOAPI = 0x0008;

class CbeffPatronFormatIdentifiers
{
	N_DECLARE_STATIC_OBJECT_CLASS(CbeffPatronFormatIdentifiers)
};

}}}

#endif // !CBEFF_PATRON_FORMAT_IDENTIFIERS_HPP_INCLUDED
