#ifndef CBEFF_COMPRESSION_ALGORITHM_IDENTIFIERS_H_INCLUDED
#define CBEFF_COMPRESSION_ALGORITHM_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

#define CBEFF_CAI_INCITS_TC_M1_BIOMETRICS_WSQ       0x8001
#define CBEFF_CAI_INCITS_TC_M1_BIOMETRICS_JPEG      0x8003
#define CBEFF_CAI_INCITS_TC_M1_BIOMETRICS_JPEG_2000 0x8004
#define CBEFF_CAI_INCITS_TC_M1_BIOMETRICS_PNG       0x8007

N_DECLARE_STATIC_OBJECT_TYPE(CbeffCompressionAlgorithmIdentifiers)

#ifdef N_CPP
}
#endif

#endif // !CBEFF_COMPRESSION_ALGORITHM_IDENTIFIERS_H_INCLUDED
