#ifndef CBEFF_BIOMETRIC_ORGANIZATIONS_HPP_INCLUDED
#define CBEFF_BIOMETRIC_ORGANIZATIONS_HPP_INCLUDED

#include <Core/NTypes.hpp>
namespace Neurotec { namespace Biometrics { namespace Standards
{
#include <Biometrics/Standards/CbeffBiometricOrganizations.h>
}}}

namespace Neurotec { namespace Biometrics { namespace Standards
{

#undef CBEFF_BO_SAFLINK
#undef CBEFF_BO_BIOSCRYPT
#undef CBEFF_BO_IDENTIX
#undef CBEFF_BO_INFINEON_TECHNOLOGIES
#undef CBEFF_BO_IRIDIAN_TECHNOLOGIES
#undef CBEFF_BO_VERIDICOM
#undef CBEFF_BO_CYBER_SIGN
#undef CBEFF_BO_ECRYP
#undef CBEFF_BO_FINGERPRINT_CARDS
#undef CBEFF_BO_SECUGEN
#undef CBEFF_BO_PRECISE_BIOMETRICS
#undef CBEFF_BO_IDENTIX_2
#undef CBEFF_BO_DERMALOG_IDENTIFICATION_SYSTEMS
#undef CBEFF_BO_LOGICO_SMARTCARD_SOLUTIONS
#undef CBEFF_BO_NIST
#undef CBEFF_BO_A_4_VISION
#undef CBEFF_BO_NEC_SOLUTIONS_AMERICA
#undef CBEFF_BO_UPEK
#undef CBEFF_BO_ULTRA_SCAN
#undef CBEFF_BO_AURORA_WIRELESS_TECHNOLOGIES
#undef CBEFF_BO_THALES_IDENITFICATION
#undef CBEFF_BO_INTERNATIONAL_BIOMETRIC_GROUP
#undef CBEFF_BO_COGENT_SYSTEMS
#undef CBEFF_BO_CROSS_MATCH_TECHNOLOGIES
#undef CBEFF_BO_RECOGNITION_SYSTEMS
#undef CBEFF_BO_GERMAN_INSTITUTE_FOR_STANDARDIZATION
#undef CBEFF_BO_INCITS_TC_M1_BIOMETRICS
#undef CBEFF_BO_NITGEN
#undef CBEFF_BO_SAGEM_MORPHO
#undef CBEFF_BO_BIOLINK_TECHNOLOGIES_INTERNATIONAL
#undef CBEFF_BO_ACTIVCARD
#undef CBEFF_BO_HUMANSCAN
#undef CBEFF_BO_ACSYS_BIOMETRICS
#undef CBEFF_BO_SILEX_TECHNOLOGY
#undef CBEFF_BO_BIO_WISE
#undef CBEFF_BO_LUMIDIGM
#undef CBEFF_BO_GUARDWARE_SYSTEMS
#undef CBEFF_BO_INVESTORSHELPERS
#undef CBEFF_BO_VALIDITY
#undef CBEFF_BO_VIISAGE
#undef CBEFF_BO_LG_ELECTRONICS_USA
#undef CBEFF_BO_STARTEK_ENGINEERING
#undef CBEFF_BO_JANUS_ASSOCIATES
#undef CBEFF_BO_OMNIPERCEPTION
#undef CBEFF_BO_MOTOROLA
#undef CBEFF_BO_CRYPTO_METRICS
#undef CBEFF_BO_BIOKEY_INTERNATIONAL
#undef CBEFF_BO_NEUROTECHNOLOGIJA
#undef CBEFF_BO_ANTHEUS_TECHNOLOGY
#undef CBEFF_BO_DIGITALPERSONA
#undef CBEFF_BO_XTEC
#undef CBEFF_BO_INNOVATRICS
#undef CBEFF_BO_EAST_SHORE_TECHNOLOGIES
#undef CBEFF_BO_HITACHI
#undef CBEFF_BO_123ID
#undef CBEFF_BO_BIOKEY_INTERNATIONAL_2
#undef CBEFF_BO_GRIAULE_TECNOLOGIA
#undef CBEFF_BO_AWARE
#undef CBEFF_BO_SONDA_TECHNOLOGIES
#undef CBEFF_BO_SECURE_DESIGN
#undef CBEFF_BO_VERIDT
#undef CBEFF_BO_ID3_SEMICONDUCTORS
#undef CBEFF_BO_GREEN_BIT_AMERICAS
#undef CBEFF_BO_ATMEL
#undef CBEFF_BO_AUTHEN_TEC
#undef CBEFF_BO_IMAGE_WARE_SYSTEMS
#undef CBEFF_BO_SUPREMA
#undef CBEFF_BO_BIOVISION
#undef CBEFF_BO_FUJITSU
#undef CBEFF_BO_AOPTIX
#undef CBEFF_BO_DIGENT
#undef CBEFF_BO_WARWICK_WARP
#undef CBEFF_BO_EASTERN_GOLDEN_FINGER_TECHNOLOGY_BEIJING
#undef CBEFF_BO_FEDERAL_OFFICE_FOR_INFORMATION_SECURITY
#undef CBEFF_BO_BIOLOGICA_SISTEMAS
#undef CBEFF_BO_FUTRONIC_TECHNOLOGY
#undef CBEFF_BO_IRITECH
#undef CBEFF_BO_KP_VTI
#undef CBEFF_BO_JFINGER
#undef CBEFF_BO_OASIS
#undef CBEFF_BO_HUTCABB_CONSULTING
#undef CBEFF_BO_BIOMETRICS_IDENTITY_MANAGEMENT_AGENCY
#undef CBEFF_BO_PRECISION_INFOMATIC
#undef CBEFF_BO_CHINA_NATIONAL_INFORMATION_TECHNOLOGY_STANDARDIZATION_TECHNICAL_COMMITTEE
#undef CBEFF_BO_DELTA_ID
#undef CBEFF_BO_BEIJING_TECHSHINO_TECHNOLOGY

#undef CBEFF_BO_ISO_IEC_JTC_1_SC_37_BIOMETRICS
#undef CBEFF_BO_ISO_IEC_JTC_1_SC_27_IT_SECURITY_TECHNIQUES

#undef CBEFF_BO_PRIVATE
#undef CBEFF_BO_TESTING_1
#undef CBEFF_BO_TESTING_2
#undef CBEFF_BO_NOT_FOR_USE

#undef CBEFF_BO_VENDOR_UNKNOWN

const NUShort CBEFF_BO_SAFLINK = 0x0001;
const NUShort CBEFF_BO_BIOSCRYPT = 0x0002;
const NUShort CBEFF_BO_IDENTIX = 0x0003;
const NUShort CBEFF_BO_INFINEON_TECHNOLOGIES = 0x0004;
const NUShort CBEFF_BO_IRIDIAN_TECHNOLOGIES = 0x0005;
const NUShort CBEFF_BO_VERIDICOM = 0x0006;
const NUShort CBEFF_BO_CYBER_SIGN = 0x0007;
const NUShort CBEFF_BO_ECRYP = 0x0008;
const NUShort CBEFF_BO_FINGERPRINT_CARDS = 0x0009;
const NUShort CBEFF_BO_SECUGEN = 0x000A;
const NUShort CBEFF_BO_PRECISE_BIOMETRICS = 0x000B;
const NUShort CBEFF_BO_IDENTIX_2 = 0x000C;
const NUShort CBEFF_BO_DERMALOG_IDENTIFICATION_SYSTEMS = 0x000D;
const NUShort CBEFF_BO_LOGICO_SMARTCARD_SOLUTIONS = 0x000E;
const NUShort CBEFF_BO_NIST = 0x000F;
const NUShort CBEFF_BO_A_4_VISION = 0x0010;
const NUShort CBEFF_BO_NEC_SOLUTIONS_AMERICA = 0x0011;
const NUShort CBEFF_BO_UPEK = 0x0012;
const NUShort CBEFF_BO_ULTRA_SCAN = 0x0013;
const NUShort CBEFF_BO_AURORA_WIRELESS_TECHNOLOGIES = 0x0014;
const NUShort CBEFF_BO_THALES_IDENITFICATION = 0x0015;
const NUShort CBEFF_BO_INTERNATIONAL_BIOMETRIC_GROUP = 0x0016;
const NUShort CBEFF_BO_COGENT_SYSTEMS = 0x0017;
const NUShort CBEFF_BO_CROSS_MATCH_TECHNOLOGIES = 0x0018;
const NUShort CBEFF_BO_RECOGNITION_SYSTEMS = 0x0019;
const NUShort CBEFF_BO_GERMAN_INSTITUTE_FOR_STANDARDIZATION = 0x001A;
const NUShort CBEFF_BO_INCITS_TC_M1_BIOMETRICS = 0x001B;
const NUShort CBEFF_BO_NITGEN = 0x001C;
const NUShort CBEFF_BO_SAGEM_MORPHO = 0x001D;
const NUShort CBEFF_BO_BIOLINK_TECHNOLOGIES_INTERNATIONAL = 0x001F;
const NUShort CBEFF_BO_ACTIVCARD = 0x0020;
const NUShort CBEFF_BO_HUMANSCAN = 0x0021;
const NUShort CBEFF_BO_ACSYS_BIOMETRICS = 0x0022;
const NUShort CBEFF_BO_SILEX_TECHNOLOGY = 0x0023;
const NUShort CBEFF_BO_BIO_WISE = 0x0024;
const NUShort CBEFF_BO_LUMIDIGM = 0x0025;
const NUShort CBEFF_BO_GUARDWARE_SYSTEMS = 0x0026;
const NUShort CBEFF_BO_INVESTORSHELPERS = 0x0027;
const NUShort CBEFF_BO_VALIDITY = 0x0028;
const NUShort CBEFF_BO_VIISAGE = 0x0029;
const NUShort CBEFF_BO_LG_ELECTRONICS_USA = 0x002A;
const NUShort CBEFF_BO_STARTEK_ENGINEERING = 0x002B;
const NUShort CBEFF_BO_JANUS_ASSOCIATES = 0x002C;
const NUShort CBEFF_BO_OMNIPERCEPTION = 0x002D;
const NUShort CBEFF_BO_MOTOROLA = 0x002E;
const NUShort CBEFF_BO_CRYPTO_METRICS = 0x002F;
const NUShort CBEFF_BO_BIOKEY_INTERNATIONAL = 0x0030;
const NUShort CBEFF_BO_NEUROTECHNOLOGIJA = 0x0031;
const NUShort CBEFF_BO_ANTHEUS_TECHNOLOGY = 0x0032;
const NUShort CBEFF_BO_DIGITALPERSONA = 0x0033;
const NUShort CBEFF_BO_XTEC = 0x0034;
const NUShort CBEFF_BO_INNOVATRICS = 0x0035;
const NUShort CBEFF_BO_EAST_SHORE_TECHNOLOGIES = 0x0036;
const NUShort CBEFF_BO_HITACHI = 0x0037;
const NUShort CBEFF_BO_123ID = 0x0038;
const NUShort CBEFF_BO_BIOKEY_INTERNATIONAL_2 = 0x0039;
const NUShort CBEFF_BO_GRIAULE_TECNOLOGIA = 0x003A;
const NUShort CBEFF_BO_AWARE = 0x003B;
const NUShort CBEFF_BO_SONDA_TECHNOLOGIES = 0x003C;
const NUShort CBEFF_BO_SECURE_DESIGN = 0x003D;
const NUShort CBEFF_BO_VERIDT = 0x003E;
const NUShort CBEFF_BO_ID3_SEMICONDUCTORS = 0x003F;
const NUShort CBEFF_BO_GREEN_BIT_AMERICAS = 0x0040;
const NUShort CBEFF_BO_ATMEL = 0x0041;
const NUShort CBEFF_BO_AUTHEN_TEC = 0x0042;
const NUShort CBEFF_BO_IMAGE_WARE_SYSTEMS = 0x0043;
const NUShort CBEFF_BO_SUPREMA = 0x0044;
const NUShort CBEFF_BO_BIOVISION = 0x0045;
const NUShort CBEFF_BO_FUJITSU = 0x0046;
const NUShort CBEFF_BO_AOPTIX = 0x0047;
const NUShort CBEFF_BO_DIGENT = 0x0048;
const NUShort CBEFF_BO_WARWICK_WARP = 0x0049;
const NUShort CBEFF_BO_EASTERN_GOLDEN_FINGER_TECHNOLOGY_BEIJING = 0x004A;
const NUShort CBEFF_BO_FEDERAL_OFFICE_FOR_INFORMATION_SECURITY = 0x004B;
const NUShort CBEFF_BO_BIOLOGICA_SISTEMAS = 0x004C;
const NUShort CBEFF_BO_FUTRONIC_TECHNOLOGY = 0x004D;
const NUShort CBEFF_BO_IRITECH = 0x004E;
const NUShort CBEFF_BO_KP_VTI = 0x004F;
const NUShort CBEFF_BO_JFINGER = 0x0050;
const NUShort CBEFF_BO_OASIS = 0x0052;
const NUShort CBEFF_BO_HUTCABB_CONSULTING = 0x0053;
const NUShort CBEFF_BO_BIOMETRICS_IDENTITY_MANAGEMENT_AGENCY = 0x0054;
const NUShort CBEFF_BO_PRECISION_INFOMATIC = 0x0055;
const NUShort CBEFF_BO_CHINA_NATIONAL_INFORMATION_TECHNOLOGY_STANDARDIZATION_TECHNICAL_COMMITTEE = 0x0056;
const NUShort CBEFF_BO_DELTA_ID = 0x0057;
const NUShort CBEFF_BO_BEIJING_TECHSHINO_TECHNOLOGY = 0x0058;

const NUShort CBEFF_BO_ISO_IEC_JTC_1_SC_37_BIOMETRICS = 0x0101;
const NUShort CBEFF_BO_ISO_IEC_JTC_1_SC_27_IT_SECURITY_TECHNIQUES = 0x0102;

const NUShort CBEFF_BO_PRIVATE = 0xFEFE;
const NUShort CBEFF_BO_TESTING_1 = 0xFFF0;
const NUShort CBEFF_BO_TESTING_2 = 0xFFFE;
const NUShort CBEFF_BO_NOT_FOR_USE = 0xFFFF;

const NUShort CBEFF_BO_VENDOR_UNKNOWN = 0x0103;

class CbeffBiometricOrganizations
{
	N_DECLARE_STATIC_OBJECT_CLASS(CbeffBiometricOrganizations)
};

}}}

#endif // !CBEFF_BIOMETRIC_ORGANIZATIONS_HPP_INCLUDED
