#ifndef CBEFF_SB_FORMAT_IDENTIFIERS_HPP_INCLUDED
#define CBEFF_SB_FORMAT_IDENTIFIERS_HPP_INCLUDED

#include <Core/NTypes.hpp>
namespace Neurotec { namespace Biometrics { namespace Standards
{
#include <Biometrics/Standards/CbeffSBFormatIdentifiers.h>
}}}

namespace Neurotec { namespace Biometrics { namespace Standards
{

#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER
#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER
#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER
#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER_SO
#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER_SO
#undef CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER_SO

const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER = 0x0001;
const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER = 0x0002;
const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER = 0x0003;
const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_DER_SO = 0x0004;
const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_PER_SO = 0x0005;
const NUShort CBEFF_SBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_GENERAL_PURPOSE_XER_SO = 0x0006;

class CbeffSBFormatIdentifiers
{
	N_DECLARE_STATIC_OBJECT_CLASS(CbeffSBFormatIdentifiers)
};

}}}

#endif // !CBEFF_SB_FORMAT_IDENTIFIERS_HPP_INCLUDED
