#ifndef CBEFF_BDB_FORMAT_IDENTIFIERS_H_INCLUDED
#define CBEFF_BDB_FORMAT_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_N                                      0x0201
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_X                                      0x0202
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FINGER_MINUTIAE_U                                      0x0203
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FINGER_PATTERN_N                                       0x0301
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FINGER_IMAGE                                           0x0401
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_FACE_IMAGE                                             0x0501
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_IRIS_RECTILINEAR                                       0x0601
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_IRIS_POLAR                                             0x0602
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_DATA_N                              0x0701
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_DATA_X                              0x0702
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_COMMON_FEATURE_DATA_N                   0x0703
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_COMMON_FEATURE_DATA_X                   0x0704
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_AND_COMMON_FEATURE_DATA_N           0x0705
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_SIGNATURE_SIGN_RAW_AND_COMMON_FEATURE_DATA_X           0x0706
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_HAND_GEOMETRY_N                                        0x0801
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_HAND_GEOMETRY_X                                        0x0802
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_BIOMETRIC_FUSION_DATA                                  0x0901
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_WSQ_IMAGE                                              0x8001
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_BMP_IMAGE                                              0x8002
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_JPEG_IMAGE                                             0x8003
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_JPEG2000_IMAGE                                         0x8004
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_TIFF_IMAGE                                             0x8005
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_GIF89A_IMAGE                                           0x8006
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_PNG_IMAGE                                              0x8007
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_WAV_AUDIO                                              0x8008
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_MPEG_MEDIA                                             0x8009
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_MPEG1_PART_3_MEDIA                                     0x800A
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_AVI_MEDIA                                              0x800B
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_VRML_3D_OBJECT_DATA                                    0x800C
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_4_RECORD                          0x800D
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_10_RECORD                         0x800E
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_13_RECORD                         0x800F
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_14_RECORD                         0x8010
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_15_RECORD                         0x8011
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_2000_TYPE_16_RECORD                         0x8012
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL_1_200X_RECORD_COLLECTION_FOR_TENPRINT_CAPTURE 0x8013
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_GENERIC_FBI_EFTS_RECORD                                0x8014
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIEM                                                   0x8015
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_10_RECORD                          0x8016
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_14_RECORD                          0x8017
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_NIST_ITL1_2007_TYPE_17_RECORD                          0x8018
#define CBEFF_BDBFI_INCITS_TC_M1_BIOMETRICS_EBTS                                                   0x8019

#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NFRECORD_1 0x0100
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NFRECORD_2 0x0101
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NFRECORD_3 0x0102
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NLRECORD_1 0x0300
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NLRECORD_2 0x0301
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NLRECORD_3 0x0302
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NERECORD_1 0x0500
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NSRECORD_1 0x0700
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NFTEMPLATE 0x0200
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NLTEMPLATE 0x0400
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NETEMPLATE 0x0600
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NSTEMPLATE 0x0800
#define CBEFF_BDBFI_NEUROTECHNOLOGIJA_NTEMPLATE  0x0000

#define CBEFF_BDBFI_ID3_SEMICONDUCTORS_COMPACT_CARD_EXTENSION 0x0001

#define CBEFF_BDBFI_FEDERAL_OFFICE_FOR_INFORMATION_SECURITY_TR_BIOMETRICS_XML_FACE_1_0   0x0001
#define CBEFF_BDBFI_FEDERAL_OFFICE_FOR_INFORMATION_SECURITY_TR_BIOMETRICS_XML_FINGER_1_0 0x0002

#define CBEFF_BDBFI_BIOLOGICA_SISTEMAS_ISO_19794_2_BIOUNISTATION 0x0002
#define CBEFF_BDBFI_BIOLOGICA_SISTEMAS_ISO_19794_4_BIOUNISTATION 0x0004
#define CBEFF_BDBFI_BIOLOGICA_SISTEMAS_ISO_19794_5_BIOUNISTATION 0x0005

#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_RECORD_N                                0x0001
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_RECORD_X                                0x0002
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_V                           0x0003
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_N                           0x0004
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_V                          0x0005
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_N                          0x0006
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_IMAGE                                            0x0007
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FACE_IMAGE                                              0x0008
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_IRIS_IMAGE_RECTILINEAR                                  0x0009
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_QUANTIZED_CO_SINUSOIDAL_TRIPLET 0x000A
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_IRIS_IMAGE_POLAR                                        0x000B
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_DISCRETE_FOURIER_TRANSFORM      0x000C
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SPECTRAL_GABOR_FILTER                    0x000D
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIGNATURE_SIGN_TIME_SERIES_FULL                         0x000E
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIGNATURE_SIGN_TIME_SERIES_COMPACT                      0x000F
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_RECORD                     0x0011
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_CARD_NORMAL                0x0012
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_PATTERN_SKELETAL_DATA_CARD_COMPACT               0x0013
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_VASCULAR_IMAGE_DATA                                     0x0014
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_HAND_GEOMETRY_SILHOUETTE                                0x0018
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_V_H                        0x0019
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_COMPACT_R_H                        0x001A
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_V_NH                        0x001B
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_CARD_NORMAL_R_NH                        0x001C
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_FINGER_MINUTIAE_RECORD_FORMAT                           0x001D
#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIGNATURE_SIGN_TIME_SERIES_COMPRESSION                  0x001E

#define CBEFF_BDBFI_ISO_IEC_JTC_1_SC_27_IT_SECURITY_TECHNIQUES_BIOMETRIC_REFERENCE_TEMPLATE_CERTIFICATE 0x0001

N_DECLARE_STATIC_OBJECT_TYPE(CbeffBdbFormatIdentifiers)

#ifdef N_CPP
}
#endif

#endif // !CBEFF_BDB_FORMAT_IDENTIFIERS_H_INCLUDED
