#ifndef CBEFF_PATRON_FORMAT_IDENTIFIERS_H_INCLUDED
#define CBEFF_PATRON_FORMAT_IDENTIFIERS_H_INCLUDED

#include <Core/NTypes.h>

#ifdef N_CPP
extern "C"
{
#endif

#define CBEFF_PFI_NIST_D 0x0001
#define CBEFF_PFI_NIST_E 0x0002

#define CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_A 0x0001
#define CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_B 0x0002
#define CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_C 0x0003
#define CBEFF_PFI_INCITS_TC_M1_BIOMETRICS_D 0x0004

#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BIT_ORIENTED    0x0001
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_SIMPLE_BYTE_ORIENTED   0x0002
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_PRESENCE_BYTE_ORIENTED 0x0003
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIT_ORIENTED           0x0004
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_TLV_ENCODED            0x0005
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_COMPLEX                0x0006
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_XML                    0x0007
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_BIOAPI                 0x0008
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_COMPLEX_WITH_ADD_ELEM  0x000A
#define CBEFF_PFI_ISO_IEC_JTC_1_SC_37_BIOMETRICS_XML_WITH_ADD_ELEM      0x000B

N_DECLARE_STATIC_OBJECT_TYPE(CbeffPatronFormatIdentifiers)

#ifdef N_CPP
}
#endif

#endif // !CBEFF_PATRON_FORMAT_IDENTIFIERS_H_INCLUDED
