#ifndef N_BIOMETRICS_LIBRARY_H_INCLUDED
#define N_BIOMETRICS_LIBRARY_H_INCLUDED

#include <Biometrics/NBiometricAttributes.h>
#include <Biometrics/NBiometricTypes.h>
#include <Biometrics/NEAttributes.h>
#include <Biometrics/NEMatchingDetails.h>
#include <Biometrics/NERecord.h>
#include <Biometrics/NETemplate.h>
#include <Biometrics/NFAttributes.h>
#include <Biometrics/NFMatchingDetails.h>
#include <Biometrics/NFRecord.h>
#include <Biometrics/NFRecordV1.h>
#include <Biometrics/NFTemplate.h>
#include <Biometrics/NLAttributes.h>
#include <Biometrics/NLMatchingDetails.h>
#include <Biometrics/NLRecord.h>
#include <Biometrics/NLTemplate.h>
#include <Biometrics/NSAttributes.h>
#include <Biometrics/NSMatchingDetails.h>
#include <Biometrics/NSRecord.h>
#include <Biometrics/NSTemplate.h>
#include <Biometrics/NMatchingDetails.h>
#include <Biometrics/NMatchingDetailsBase.h>
#include <Biometrics/NTemplate.h>
#include <Biometrics/NXMatchingDetails.h>
#include <Biometrics/NBiometric.h>
#include <Biometrics/NFrictionRidge.h>
#include <Biometrics/NFinger.h>
#include <Biometrics/NPalm.h>
#include <Biometrics/NFace.h>
#include <Biometrics/NIris.h>
#include <Biometrics/NVoice.h>
#include <Biometrics/NSubject.h>
#include <Biometrics/NMatchingResult.h>
#include <Biometrics/NBiometricConnection.h>
#include <Biometrics/NBiometricTask.h>
#include <Biometrics/NBiometricEngine.h>
#include <Biometrics/NBiometrics.h>
#include <Biometrics/Standards/CbeffBiometricOrganizations.h>
#include <Biometrics/Standards/CbeffPatronFormatIdentifiers.h>
#include <Biometrics/Standards/CbeffBdbFormatIdentifiers.h>
#include <Biometrics/Standards/CbeffQualityAlgorithmIdentifiers.h>
#include <Biometrics/Standards/CbeffCompressionAlgorithmIdentifiers.h>
#include <Biometrics/Standards/CbeffSBFormatIdentifiers.h>
#include <Biometrics/Standards/CbeffRecord.h>
#include <Biometrics/Standards/BdifTypes.h>
#include <Biometrics/Standards/FMRecord.h>
#include <Biometrics/Standards/FmrFingerView.h>
#include <Biometrics/Standards/FIRecord.h>
#include <Biometrics/Standards/FirFingerView.h>
#include <Biometrics/Standards/FCRecord.h>
#include <Biometrics/Standards/FcrFaceImage.h>
#include <Biometrics/Standards/IIRecord.h>
#include <Biometrics/Standards/IirIrisImage.h>
#include <Biometrics/Standards/ANTemplate.h>
#include <Biometrics/Standards/ANRecordType.h>
#include <Biometrics/Standards/ANSubField.h>
#include <Biometrics/Standards/ANField.h>
//#include <Biometrics/Standards/ANRecord.h>
#include <Biometrics/Standards/ANAsciiRecord.h>
#include <Biometrics/Standards/ANBinaryRecord.h>
#include <Biometrics/Standards/ANAsciiBinaryRecord.h>
#include <Biometrics/Standards/ANImage.h>
#include <Biometrics/Standards/ANImageBinaryRecord.h>
#include <Biometrics/Standards/ANImageAsciiBinaryRecord.h>
#include <Biometrics/Standards/ANFImageBinaryRecord.h>
#include <Biometrics/Standards/ANFPImageAsciiBinaryRecord.h>
#include <Biometrics/Standards/ANType1Record.h>
#include <Biometrics/Standards/ANType2Record.h>
#include <Biometrics/Standards/ANType3Record.h>
#include <Biometrics/Standards/ANType4Record.h>
#include <Biometrics/Standards/ANType5Record.h>
#include <Biometrics/Standards/ANType6Record.h>
#include <Biometrics/Standards/ANType7Record.h>
#include <Biometrics/Standards/ANType8Record.h>
#include <Biometrics/Standards/ANType9Record.h>
#include <Biometrics/Standards/ANType10Record.h>
#include <Biometrics/Standards/ANType13Record.h>
#include <Biometrics/Standards/ANType14Record.h>
#include <Biometrics/Standards/ANType15Record.h>
#include <Biometrics/Standards/ANType16Record.h>
#include <Biometrics/Standards/ANType17Record.h>
#include <Biometrics/Standards/ANType99Record.h>

#endif // !N_BIOMETRICS_LIBRARY_H_INCLUDED
