#ifndef N_BIOMETRICS_LIBRARY_HPP_INCLUDED
#define N_BIOMETRICS_LIBRARY_HPP_INCLUDED

#include <Biometrics/NBiometricAttributes.hpp>
#include <Biometrics/NBiometricTypes.hpp>
#include <Biometrics/NEAttributes.hpp>
#include <Biometrics/NEMatchingDetails.hpp>
#include <Biometrics/NERecord.hpp>
#include <Biometrics/NETemplate.hpp>
#include <Biometrics/NFAttributes.hpp>
#include <Biometrics/NFMatchingDetails.hpp>
#include <Biometrics/NFRecord.hpp>
#include <Biometrics/NFTemplate.hpp>
#include <Biometrics/NLAttributes.hpp>
#include <Biometrics/NLMatchingDetails.hpp>
#include <Biometrics/NLRecord.hpp>
#include <Biometrics/NLTemplate.hpp>
#include <Biometrics/NSAttributes.hpp>
#include <Biometrics/NSMatchingDetails.hpp>
#include <Biometrics/NSRecord.hpp>
#include <Biometrics/NSTemplate.hpp>
#include <Biometrics/NMatchingDetails.hpp>
#include <Biometrics/NMatchingDetailsBase.hpp>
#include <Biometrics/NTemplate.hpp>
#include <Biometrics/NXMatchingDetails.hpp>
#include <Biometrics/NBiometric.hpp>
#include <Biometrics/NFinger.hpp>
#include <Biometrics/NPalm.hpp>
#include <Biometrics/NFace.hpp>
#include <Biometrics/NIris.hpp>
#include <Biometrics/NVoice.hpp>
#include <Biometrics/NSubject.hpp>
#include <Biometrics/NMatchingResult.hpp>
#include <Biometrics/NBiometricConnection.hpp>
#include <Biometrics/NBiometricTask.hpp>
#include <Biometrics/NBiometricEngine.hpp>
#include <Biometrics/NBiometrics.hpp>
#include <Biometrics/Standards/CbeffBiometricOrganizations.hpp>
#include <Biometrics/Standards/CbeffPatronFormatIdentifiers.hpp>
#include <Biometrics/Standards/CbeffBdbFormatIdentifiers.hpp>
#include <Biometrics/Standards/CbeffQualityAlgorithmIdentifiers.hpp>
#include <Biometrics/Standards/CbeffCompressionAlgorithmIdentifiers.hpp>
#include <Biometrics/Standards/CbeffSBFormatIdentifiers.hpp>
#include <Biometrics/Standards/CbeffRecord.hpp>
#include <Biometrics/Standards/BdifTypes.hpp>
#include <Biometrics/Standards/FMRecord.hpp>
#include <Biometrics/Standards/FmrFingerView.hpp>
#include <Biometrics/Standards/FIRecord.hpp>
#include <Biometrics/Standards/FirFingerView.hpp>
#include <Biometrics/Standards/FCRecord.hpp>
#include <Biometrics/Standards/FcrFaceImage.hpp>
#include <Biometrics/Standards/IIRecord.hpp>
#include <Biometrics/Standards/IirIrisImage.hpp>
#include <Biometrics/Standards/ANTemplate.hpp>
#include <Biometrics/Standards/ANRecordType.hpp>
#include <Biometrics/Standards/ANSubField.hpp>
#include <Biometrics/Standards/ANField.hpp>
#include <Biometrics/Standards/ANRecord.hpp>
#include <Biometrics/Standards/ANAsciiRecord.hpp>
#include <Biometrics/Standards/ANBinaryRecord.hpp>
#include <Biometrics/Standards/ANAsciiBinaryRecord.hpp>
#include <Biometrics/Standards/ANImage.hpp>
#include <Biometrics/Standards/ANImageBinaryRecord.hpp>
#include <Biometrics/Standards/ANImageAsciiBinaryRecord.hpp>
#include <Biometrics/Standards/ANFImageBinaryRecord.hpp>
#include <Biometrics/Standards/ANFPImageAsciiBinaryRecord.hpp>
#include <Biometrics/Standards/ANType1Record.hpp>
#include <Biometrics/Standards/ANType2Record.hpp>
#include <Biometrics/Standards/ANType3Record.hpp>
#include <Biometrics/Standards/ANType4Record.hpp>
#include <Biometrics/Standards/ANType5Record.hpp>
#include <Biometrics/Standards/ANType6Record.hpp>
#include <Biometrics/Standards/ANType7Record.hpp>
#include <Biometrics/Standards/ANType8Record.hpp>
#include <Biometrics/Standards/ANType9Record.hpp>
#include <Biometrics/Standards/ANType10Record.hpp>
#include <Biometrics/Standards/ANType13Record.hpp>
#include <Biometrics/Standards/ANType14Record.hpp>
#include <Biometrics/Standards/ANType15Record.hpp>
#include <Biometrics/Standards/ANType16Record.hpp>
#include <Biometrics/Standards/ANType17Record.hpp>
#include <Biometrics/Standards/ANType99Record.hpp>

#endif // !N_BIOMETRICS_LIBRARY_HPP_INCLUDED
