#ifndef N_CORE_LIBRARY_HPP_INCLUDED
#define N_CORE_LIBRARY_HPP_INCLUDED

#include <Collections/NCollection.hpp>
#include <Collections/NDictionary.hpp>
#include <Collections/NArrayCollection.hpp>
#include <Collections/NList.hpp>
#include <Collections/NListList.hpp>
#include <Collections/NQueue.hpp>
#include <Collections/NStack.hpp>
#include <Collections/NCollections.hpp>
#include <ComponentModel/NDescriptor.hpp>
#include <ComponentModel/NParameterDescriptor.hpp>
#include <ComponentModel/NMemberDescriptor.hpp>
#include <ComponentModel/NMethodDescriptor.hpp>
#include <ComponentModel/NPropertyDescriptor.hpp>
#include <ComponentModel/NEventDescriptor.hpp>
#include <ComponentModel/NCustomParameterDescriptor.hpp>
#include <ComponentModel/NCustomMethodDescriptor.hpp>
#include <ComponentModel/NCustomPropertyDescriptor.hpp>
#include <ComponentModel/NCustomEventDescriptor.hpp>
#include <ComponentModel/NTypeDescriptor.hpp>
#include <ComponentModel/NParameterBag.hpp>
#include <Core/NTypes.hpp>
#include <Core/NError.hpp>
#include <Core/NMemory.hpp>
#include <Core/NObject.hpp>
#include <Core/NObjectPart.hpp>
#include <Core/NCore.hpp>
#include <Core/NWeakReference.hpp>
#include <Core/NEvent.hpp>
#include <Core/NType.hpp>
#include <Core/NValue.hpp>
#include <Core/NArray.hpp>
#include <Core/NPropertyBag.hpp>
#include <Core/NExpandableObject.hpp>
#include <Core/NEnum.hpp>
#include <Core/NModule.hpp>
#include <Core/NAsyncOperation.hpp>
#include <Core/NProcessorInfo.hpp>
#include <Core/NString.hpp>
#include <Core/NCallback.hpp>
#include <Core/NTimeSpan.hpp>
#include <Core/NDateTime.hpp>
#include <Interop/NWindows.hpp>
#include <Core/NEnvironment.hpp>
#include <Core/NConsole.hpp>
#include <Core/NReDeprecate.h>
#include <Diagnostics/NStopwatch.hpp>
#include <IO/NIOTypes.hpp>
#include <IO/NStream.hpp>
#include <IO/NFileStream.hpp>
#include <IO/NMemoryStream.hpp>
#include <IO/NBufferedStream.hpp>
#include <IO/NCustomStream.hpp>
#include <IO/NBinaryReader.hpp>
#include <IO/NBinaryWriter.hpp>
#include <IO/NBuffer.hpp>
#include <IO/NFile.hpp>
#include <IO/NFileEnumerator.hpp>
#include <IO/NDirectory.hpp>
#include <IO/NPath.hpp>
#include <IO/NTextReader.hpp>
#include <IO/NTextWriter.hpp>
#include <IO/NStreamReader.hpp>
#include <IO/NStreamWriter.hpp>
#include <IO/NStringReader.hpp>
#include <IO/NStringWriter.hpp>
#include <Plugins/ComponentModel/NPluginMethodDescriptor.hpp>
#include <Plugins/ComponentModel/NPluginPropertyDescriptor.hpp>
#include <Plugins/ComponentModel/NPluginEventDescriptor.hpp>
#include <Plugins/NPluginModule.hpp>
#include <Plugins/NPlugin.hpp>
#include <Plugins/NPluginManager.hpp>
#include <Reflection/NParameterInfo.hpp>
#include <Reflection/NMemberInfo.hpp>
#include <Reflection/NConstantInfo.hpp>
#include <Reflection/NEnumConstantInfo.hpp>
#include <Reflection/NMethodInfo.hpp>
#include <Reflection/NPropertyInfo.hpp>
#include <Reflection/NEventInfo.hpp>
#include <Reflection/NObjectPartInfo.hpp>
#include <Reflection/NCollectionInfo.hpp>
#include <Reflection/NDictionaryInfo.hpp>
#include <Reflection/NArrayCollectionInfo.hpp>
#include <Text/NEncoding.hpp>
#include <Text/NStringBuilder.hpp>
#include <Threading/NMonitor.hpp>
#include <Threading/NInterlocked.hpp>
#include <Threading/NRWLock.hpp>
#include <Threading/NWaitObject.hpp>
#include <Threading/NMutex.hpp>
#include <Threading/NSemaphore.hpp>
#include <Threading/NSyncEvent.hpp>
#include <Threading/NThread.hpp>
#include <Threading/NTls.hpp>

#endif // !N_CORE_LIBRARY_HPP_INCLUDED
