#ifndef N_FACE_VERIFICATION_LIBRARY_HPP_INCLUDED
#define N_FACE_VERIFICATION_LIBRARY_HPP_INCLUDED

#include <FaceVerification/NFaceVerification.hpp>

#endif // !N_FACE_VERIFICATION_LIBRARY_HPP_INCLUDED
