//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neurotec.Samples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neurotec.Samples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TenPrintCard color=&quot;blue&quot;&gt;
        ///
        ///	&lt;block x=&quot;0&quot; y=&quot;0&quot; width=&quot;620&quot; height=&quot;61&quot;&gt;
        ///		&lt;cell width=&quot;127&quot;&gt;
        ///			&lt;text value=&quot;APPLICANT&quot; size=&quot;10&quot; alignment=&quot;center&quot; bold=&quot;true&quot;/&gt;
        ///			&lt;text value=&quot;FD-258 (REV.12-10-07)&quot; size=&quot;5&quot; alignment=&quot;bottom,left&quot;/&gt;
        ///		&lt;/cell&gt;
        ///		&lt;cell width=&quot;172&quot;&gt;
        ///			&lt;text value=&quot;LEAVE BLANK&quot; size=&quot;8&quot; alignment=&quot;top,center&quot;/&gt;
        ///		&lt;/cell&gt;
        ///		&lt;cell width=&quot;321&quot;&gt;
        ///			&lt;text value=&quot;TYPE OR PRINT ALL INFORMATION IN BLACK&quot; size=&quot;8&quot; alignment=&quot;center,top&quot;/&gt;
        ///			&lt;text value=&quot;LAST NAME                      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicantCard {
            get {
                return ResourceManager.GetString("ApplicantCard", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap closeMouseOn {
            get {
                object obj = ResourceManager.GetObject("closeMouseOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TenPrintCard color=&quot;red&quot;&gt;
        ///	&lt;block x=&quot;0&quot; y=&quot;0&quot; width=&quot;322&quot; height=&quot;82&quot;&gt;
        ///		&lt;cell&gt;
        ///			&lt;text value=&quot;LEAVE BLANK          CRIMINAL&quot; size=&quot;8&quot; alignment=&quot;top,CENTER&quot; bold=&quot;true&quot;/&gt;
        ///		&lt;/cell&gt;
        ///	&lt;/block&gt;
        ///
        ///	&lt;block x=&quot;0&quot; y=&quot;65&quot; width=&quot;322&quot; height=&quot;17&quot;&gt;
        ///		&lt;cell width =&quot;68&quot;/&gt;
        ///		&lt;cell width=&quot;254&quot; drawRect=&quot;false&quot;&gt;
        ///			&lt;text value=&quot;FD-249 (Rev. 3-1-10)&quot; size=&quot;6&quot; alignment=&quot;bottom,left&quot; bold=&quot;true&quot;/&gt;
        ///		&lt;/cell&gt;
        ///	&lt;/block&gt;
        ///	
        ///	&lt;block x=&quot;322&quot; y=&quot;0&quot; width=&quot;307&quot; height=&quot;82&quot;&gt;
        ///		&lt;cell height=&quot;32&quot; drawRect=&quot;false&quot;&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CriminalCard {
            get {
                return ResourceManager.GetString("CriminalCard", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Get {
            get {
                object obj = ResourceManager.GetObject("Get", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToNext {
            get {
                object obj = ResourceManager.GetObject("GoToNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoToPrevious {
            get {
                object obj = ResourceManager.GetObject("GoToPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Hands {
            get {
                object obj = ResourceManager.GetObject("Hands", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewDocumentHS {
            get {
                object obj = ResourceManager.GetObject("NewDocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newSource {
            get {
                object obj = ResourceManager.GetObject("newSource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openfolderHS {
            get {
                object obj = ResourceManager.GetObject("openfolderHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remove {
            get {
                object obj = ResourceManager.GetObject("remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TenPrintCard color=&quot;red&quot;&gt;
        ///
        ///	&lt;block x=&quot;0&quot; y =&quot;0&quot; width=&quot;800&quot; height=&quot;508&quot; isFingerBlock=&quot;true&quot;&gt;
        ///		&lt;cell width=&quot;161&quot; height=&quot;154&quot; fingerNo=&quot;1&quot;/&gt;
        ///		&lt;cell width=&quot;161&quot; height=&quot;154&quot; fingerNo=&quot;2&quot;/&gt;
        ///		&lt;cell width=&quot;160&quot; height=&quot;154&quot; fingerNo=&quot;3&quot;/&gt;
        ///		&lt;cell width=&quot;161&quot; height=&quot;154&quot; fingerNo=&quot;4&quot;/&gt;
        ///		&lt;cell width=&quot;157&quot; height=&quot;154&quot; fingerNo=&quot;5&quot;/&gt;
        ///		&lt;cell width=&quot;161&quot; height=&quot;150&quot; fingerNo=&quot;6&quot;/&gt;
        ///		&lt;cell width=&quot;161&quot; height=&quot;150&quot; fingerNo=&quot;7&quot;/&gt;
        ///		&lt;cell width=&quot;160&quot; height=&quot;150&quot; fingerNo=&quot;8&quot;/&gt;
        ///		&lt;cell width=&quot;161&quot; h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TenPrintCard {
            get {
                return ResourceManager.GetString("TenPrintCard", resourceCulture);
            }
        }
    }
}
