include ../../../Common/Build/config.mk

### target ###

TARGET_NAME   = ReadVideo

### Objects, sources ###

# C source files

CSRCS = \
	ReadVideo.c

ifeq ($(N_MAC_OSX_FRAMEWORKS),yes)
  LDLIBS ?= -framework NMedia -framework NCore -framework NLicensing
else
  LDLIBS ?= -lNMedia -lNCore -lNLicensing
endif

include ../../../Common/Build/rules.mk

