include ../../../Common/Build/config.mk

### target ###

TARGET_NAME   = ANTemplateType10FromNImage

CFLAGS += -w

### Objects, sources ###

# C source files

CSRCS = \
	ANTemplateType10FromNImage.c

ifeq ($(N_MAC_OSX_FRAMEWORKS),yes)
  LDLIBS ?= -framework NBiometricClient -framework NBiometrics -framework NMedia -framework NCore -framework NLicensing
else
  LDLIBS ?= -lNBiometricClient -lNBiometrics -lNMedia -lNCore -lNLicensing
endif

include ../../../Common/Build/rules.mk

