#ifndef N_SMART_CARDS_DATA_ELEMENTS_HPP_INCLUDED
#define N_SMART_CARDS_DATA_ELEMENTS_HPP_INCLUDED

#include <SmartCards/BerTlv.hpp>
namespace Neurotec { namespace SmartCards
{
#include <SmartCards/NSmartCardsDataElements.h>
}}

namespace Neurotec { namespace SmartCards
{

#undef SCARD_TAG_COUNTRY_CODE_AND_NATIONAL_DATA
#undef SCARD_TAG_ISSUER_IDENTIFICATION_NUMBER
#undef SCARD_TAG_CARD_SERVICE_DATA
#undef SCARD_TAG_INITIAL_ACCESS_DATA
#undef SCARD_TAG_CARD_ISSUERS_DATA
#undef SCARD_TAG_PRE_ISSUING_DATA
#undef SCARD_TAG_CARD_CAPABILITIES
#undef SCARD_TAG_STATUS_INFORMATION
#undef SCARD_TAG_APPLICATION_FAMILY_IDENTIFIER
#undef SCARD_TAG_EXTENDED_HEADER_LIST
#undef SCARD_TAG_APPLICATION_IDENTIFIER
#undef SCARD_TAG_APPLICATION_LABEL
#undef SCARD_TAG_FILE_REFERENCE
#undef SCARD_TAG_COMMAND_TO_PERFORM
#undef SCARD_TAG_DISCRETIONARY_DATA
#undef SCARD_TAG_OFFSET_DATA_OBJECT
#undef SCARD_TAG_APPLICATION_TRACK_1
#undef SCARD_TAG_APPLICATION_TRACK_2
#undef SCARD_TAG_APPLICATION_TRACK_3
#undef SCARD_TAG_CARD_EXPIRATION_DATE
#undef SCARD_TAG_PRIMARY_ACCOUNT_NUMBER
#undef SCARD_TAG_NAME
#undef SCARD_TAG_TAG_LIST
#undef SCARD_TAG_HEADER_LIST
#undef SCARD_TAG_LOGIN_DATA_PROPRIETARY
#undef SCARD_TAG_CARDHOLDER_NAME
#undef SCARD_TAG_CARD_TRACK_1
#undef SCARD_TAG_CARD_TRACK_2
#undef SCARD_TAG_CARD_TRACK_3
#undef SCARD_TAG_APPLICATION_EXPIRATION_DATE
#undef SCARD_TAG_APPLICATION_EFFECTIVE_DATE
#undef SCARD_TAG_CARD_EFFECTIVE_DATE
#undef SCARD_TAG_INTERCHANGE_CONTROL
#undef SCARD_TAG_COUNTRY_CODE
#undef SCARD_TAG_INTERCHANGE_PROFILE
#undef SCARD_TAG_CURRENCY_CODE
#undef SCARD_TAG_DATE_OF_BIRTH
#undef SCARD_TAG_CARDHOLDER_NATIONALITY
#undef SCARD_TAG_LANGUAGE_PREFERENCES
#undef SCARD_TAG_CARDHOLDER_BIOMETRIC_DATA
#undef SCARD_TAG_PIN_USAGE_POLICY
#undef SCARD_TAG_SERVICE_CODE
#undef SCARD_TAG_TRANSACTION_COUNTER
#undef SCARD_TAG_TRANSACTION_DATE
#undef SCARD_TAG_CARD_SEQUENCE_NUMBER
#undef SCARD_TAG_SEX
#undef SCARD_TAG_CURRENCY_EXPONENT
#undef SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION
#undef SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION_FIRST_ASSOCIATED_DATA
#undef SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION_SECOND_ASSOCIATED_DATA
#undef SCARD_TAG_DYNAMIC_INTERNAL_AUTHENTICATION
#undef SCARD_TAG_DYNAMIC_EXTERNAL_AUTHENTICATION
#undef SCARD_TAG_DYNAMIC_MUTUAL_AUTHENTICATION
#undef SCARD_TAG_CARDHOLDER_PORTRAIT_IMAGE
#undef SCARD_TAG_ELEMENT_LIST
#undef SCARD_TAG_ADDRESS
#undef SCARD_TAG_CARDHOLDER_HANDWRITTEN_SIGNATURE_IMAGE
#undef SCARD_TAG_APPLICATION_IMAGE
#undef SCARD_TAG_DISPLAY_MESSAGE
#undef SCARD_TAG_TIMER
#undef SCARD_TAG_MESSAGE_REFERENCE
#undef SCARD_TAG_CARDHOLDER_PRIVATE_KEY
#undef SCARD_TAG_CARDHOLDER_PUBLIC_KEY
#undef SCARD_TAG_PUBLIC_KEY_OF_CERTIFICATION_AUTHORITY
#undef SCARD_TAG_DEPRECATED
#undef SCARD_TAG_CERTIFICATE_HOLDER_AUTHORIZATION
#undef SCARD_TAG_INTEGRATED_CIRCUIT_MANUFACTURER_IDENTIFIER
#undef SCARD_TAG_CERTIFICATE_CONTENT
#undef SCARD_TAG_UNIFORM_RESOURCE_LOCATOR
#undef SCARD_TAG_ANSWER_TO_RESET
#undef SCARD_TAG_HISTORICAL_BYTES
#undef SCARD_TAG_INTERNATIONAL_BANK_ACCOUNT_NUMBER
#undef SCARD_TAG_BANK_IDENTIFIER_CODE
#undef SCARD_TAG_COUNTRY_CODE_ALPHA2_FORMAT
#undef SCARD_TAG_COUNTRY_CODE_ALPHA3_FORMAT
#undef SCARD_TAG_ACCOUNT_TYPE
#undef SCARD_TAG_DIGITAL_SIGNATURE
#undef SCARD_TAG_APPLICATION_TEMPLATE
#undef SCARD_TAG_FCP_TEMPLATE
#undef SCARD_TAG_WRAPPER
#undef SCARD_TAG_FMD_TEMPLATE
#undef SCARD_TAG_CARDHOLDER_RELATED_DATA
#undef SCARD_TAG_CARD_DATA
#undef SCARD_TAG_AUTHENTICATION_DATA
#undef SCARD_TAG_SPECIAL_USER_REQUIREMENTS
#undef SCARD_TAG_LOGIN_TEMPLATE
#undef SCARD_TAG_QUALIFIED_NAME
#undef SCARD_TAG_CARDHOLDER_IMAGE_TEMPLATE
#undef SCARD_TAG_APPLICATION_IMAGE_TEMPLATE
#undef SCARD_TAG_APPLICATION_RELATED_DATA
#undef SCARD_TAG_FCI_TEMPLATE
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_70
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_71
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_72
#undef SCARD_TAG_DISCRETIONARY_DATA_OBJECTS
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_74
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_75
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_76
#undef SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_77
#undef SCARD_TAG_COMPATIBLE_TAG_ALLOCATION_AUTHORITY
#undef SCARD_TAG_COEXISTENT_TAG_ALLOCATION_AUTHORITY
#undef SCARD_TAG_SECURITY_SUPPORT_TEMPLATE
#undef SCARD_TAG_SECURITY_ENVIRONMENT_TEMPLATE
#undef SCARD_TAG_DYNAMIC_AUTHENTICATION_TEMPLATE
#undef SCARD_TAG_SECURE_MESSAGING_TEMPLATE
#undef SCARD_TAG_INTERINDUSTRY_DATA_OBJECTS
#undef SCARD_TAG_DISPLAY_CONTROL
#undef SCARD_TAG_CARDHOLDER_CERTIFICATE
#undef SCARD_TAG_CARDHOLDER_REQUIREMENTS_INCLUDED_FEATURES
#undef SCARD_TAG_CARDHOLDER_REQUIREMENTS_EXCLUDED_FEATURES
#undef SCARD_TAG_BIOMETRIC_DATA_TEMPLATE
#undef SCARD_TAG_DIGITAL_SIGNATURE_BLOCK
#undef SCARD_TAG_CARDHOLDER_PRIVATE_KEY_TEMPLATE
#undef SCARD_TAG_CARDHOLDER_PUBLIC_KEY_TEMPLATE
#undef SCARD_TAG_CERTIFICATE_CONTENT_TEMPLATE
#undef SCARD_TAG_BIOMETRIC_INFORMATION_TEMPLATE
#undef SCARD_TAG_BIOMETRIC_INFORMATION_GROUP_TEMPLATE

const BerTag SCARD_TAG_COUNTRY_CODE_AND_NATIONAL_DATA(0x41);
const BerTag SCARD_TAG_ISSUER_IDENTIFICATION_NUMBER(0x42);
const BerTag SCARD_TAG_CARD_SERVICE_DATA(0x43);
const BerTag SCARD_TAG_INITIAL_ACCESS_DATA(0x44);
const BerTag SCARD_TAG_CARD_ISSUERS_DATA(0x45);
const BerTag SCARD_TAG_PRE_ISSUING_DATA(0x46);
const BerTag SCARD_TAG_CARD_CAPABILITIES(0x47);
const BerTag SCARD_TAG_STATUS_INFORMATION(0x48);
const BerTag SCARD_TAG_APPLICATION_FAMILY_IDENTIFIER(0x49);
const BerTag SCARD_TAG_EXTENDED_HEADER_LIST(0x4D);
const BerTag SCARD_TAG_APPLICATION_IDENTIFIER(0x4F);
const BerTag SCARD_TAG_APPLICATION_LABEL(0x50);
const BerTag SCARD_TAG_FILE_REFERENCE(0x51);
const BerTag SCARD_TAG_COMMAND_TO_PERFORM(0x52);
const BerTag SCARD_TAG_DISCRETIONARY_DATA(0x53);
const BerTag SCARD_TAG_OFFSET_DATA_OBJECT(0x54);
const BerTag SCARD_TAG_APPLICATION_TRACK_1(0x56);
const BerTag SCARD_TAG_APPLICATION_TRACK_2(0x57);
const BerTag SCARD_TAG_APPLICATION_TRACK_3(0x58);
const BerTag SCARD_TAG_CARD_EXPIRATION_DATE(0x59);
const BerTag SCARD_TAG_PRIMARY_ACCOUNT_NUMBER(0x5A);
const BerTag SCARD_TAG_NAME(0x5B);
const BerTag SCARD_TAG_TAG_LIST(0x5C);
const BerTag SCARD_TAG_HEADER_LIST(0x5D);
const BerTag SCARD_TAG_LOGIN_DATA_PROPRIETARY(0x5E);
const BerTag SCARD_TAG_CARDHOLDER_NAME(0x5F20);
const BerTag SCARD_TAG_CARD_TRACK_1(0x5F21);
const BerTag SCARD_TAG_CARD_TRACK_2(0x5F22);
const BerTag SCARD_TAG_CARD_TRACK_3(0x5F23);
const BerTag SCARD_TAG_APPLICATION_EXPIRATION_DATE(0x5F24);
const BerTag SCARD_TAG_APPLICATION_EFFECTIVE_DATE(0x5F25);
const BerTag SCARD_TAG_CARD_EFFECTIVE_DATE(0x5F26);
const BerTag SCARD_TAG_INTERCHANGE_CONTROL(0x5F27);
const BerTag SCARD_TAG_COUNTRY_CODE(0x5F28);
const BerTag SCARD_TAG_INTERCHANGE_PROFILE(0x5F29);
const BerTag SCARD_TAG_CURRENCY_CODE(0x5F2A);
const BerTag SCARD_TAG_DATE_OF_BIRTH(0x5F2B);
const BerTag SCARD_TAG_CARDHOLDER_NATIONALITY(0x5F2C);
const BerTag SCARD_TAG_LANGUAGE_PREFERENCES(0x5F2D);
const BerTag SCARD_TAG_CARDHOLDER_BIOMETRIC_DATA(0x5F2E);
const BerTag SCARD_TAG_PIN_USAGE_POLICY(0x5F2F);
const BerTag SCARD_TAG_SERVICE_CODE(0x5F30);
const BerTag SCARD_TAG_TRANSACTION_COUNTER(0x5F32);
const BerTag SCARD_TAG_TRANSACTION_DATE(0x5F33);
const BerTag SCARD_TAG_CARD_SEQUENCE_NUMBER(0x5F34);
const BerTag SCARD_TAG_SEX(0x5F35);
const BerTag SCARD_TAG_CURRENCY_EXPONENT(0x5F36);
const BerTag SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION(0x5F37);
const BerTag SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION_FIRST_ASSOCIATED_DATA(0x5F38);
const BerTag SCARD_TAG_STATIC_INTERNAL_AUTHENTICATION_SECOND_ASSOCIATED_DATA(0x5F39);
const BerTag SCARD_TAG_DYNAMIC_INTERNAL_AUTHENTICATION(0x5F3A);
const BerTag SCARD_TAG_DYNAMIC_EXTERNAL_AUTHENTICATION(0x5F3B);
const BerTag SCARD_TAG_DYNAMIC_MUTUAL_AUTHENTICATION(0x5F3C);
const BerTag SCARD_TAG_CARDHOLDER_PORTRAIT_IMAGE(0x5F40);
const BerTag SCARD_TAG_ELEMENT_LIST(0x5F41);
const BerTag SCARD_TAG_ADDRESS(0x5F42);
const BerTag SCARD_TAG_CARDHOLDER_HANDWRITTEN_SIGNATURE_IMAGE(0x5F43);
const BerTag SCARD_TAG_APPLICATION_IMAGE(0x5F44);
const BerTag SCARD_TAG_DISPLAY_MESSAGE(0x5F45);
const BerTag SCARD_TAG_TIMER(0x5F46);
const BerTag SCARD_TAG_MESSAGE_REFERENCE(0x5F47);
const BerTag SCARD_TAG_CARDHOLDER_PRIVATE_KEY(0x5F48);
const BerTag SCARD_TAG_CARDHOLDER_PUBLIC_KEY(0x5F49);
const BerTag SCARD_TAG_PUBLIC_KEY_OF_CERTIFICATION_AUTHORITY(0x5F4A);
const BerTag SCARD_TAG_DEPRECATED(0x5F4B);
const BerTag SCARD_TAG_CERTIFICATE_HOLDER_AUTHORIZATION(0x5F4C);
const BerTag SCARD_TAG_INTEGRATED_CIRCUIT_MANUFACTURER_IDENTIFIER(0x5F4D);
const BerTag SCARD_TAG_CERTIFICATE_CONTENT(0x5F4E);
const BerTag SCARD_TAG_UNIFORM_RESOURCE_LOCATOR(0x5F50);
const BerTag SCARD_TAG_ANSWER_TO_RESET(0x5F51);
const BerTag SCARD_TAG_HISTORICAL_BYTES(0x5F52);
const BerTag SCARD_TAG_INTERNATIONAL_BANK_ACCOUNT_NUMBER(0x5F53);
const BerTag SCARD_TAG_BANK_IDENTIFIER_CODE(0x5F54);
const BerTag SCARD_TAG_COUNTRY_CODE_ALPHA2_FORMAT(0x5F55);
const BerTag SCARD_TAG_COUNTRY_CODE_ALPHA3_FORMAT(0x5F56);
const BerTag SCARD_TAG_ACCOUNT_TYPE(0x5F57);
const BerTag SCARD_TAG_DIGITAL_SIGNATURE(0x5F3D);
const BerTag SCARD_TAG_APPLICATION_TEMPLATE(0x61);
const BerTag SCARD_TAG_FCP_TEMPLATE(0x62);
const BerTag SCARD_TAG_WRAPPER(0x63);
const BerTag SCARD_TAG_FMD_TEMPLATE(0x64);
const BerTag SCARD_TAG_CARDHOLDER_RELATED_DATA(0x65);
const BerTag SCARD_TAG_CARD_DATA(0x66);
const BerTag SCARD_TAG_AUTHENTICATION_DATA(0x67);
const BerTag SCARD_TAG_SPECIAL_USER_REQUIREMENTS(0x68);
const BerTag SCARD_TAG_LOGIN_TEMPLATE(0x6A);
const BerTag SCARD_TAG_QUALIFIED_NAME(0x6B);
const BerTag SCARD_TAG_CARDHOLDER_IMAGE_TEMPLATE(0x6C);
const BerTag SCARD_TAG_APPLICATION_IMAGE_TEMPLATE(0x6D);
const BerTag SCARD_TAG_APPLICATION_RELATED_DATA(0x6E);
const BerTag SCARD_TAG_FCI_TEMPLATE(0x6F);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_70(0x70);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_71(0x71);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_72(0x72);
const BerTag SCARD_TAG_DISCRETIONARY_DATA_OBJECTS(0x73);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_74(0x74);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_75(0x75);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_76(0x76);
const BerTag SCARD_TAG_NON_INTERINDUSTRY_DATA_OBJECTS_77(0x77);
const BerTag SCARD_TAG_COMPATIBLE_TAG_ALLOCATION_AUTHORITY(0x78);
const BerTag SCARD_TAG_COEXISTENT_TAG_ALLOCATION_AUTHORITY(0x79);
const BerTag SCARD_TAG_SECURITY_SUPPORT_TEMPLATE(0x7A);
const BerTag SCARD_TAG_SECURITY_ENVIRONMENT_TEMPLATE(0x7B);
const BerTag SCARD_TAG_DYNAMIC_AUTHENTICATION_TEMPLATE(0x7C);
const BerTag SCARD_TAG_SECURE_MESSAGING_TEMPLATE(0x7D);
const BerTag SCARD_TAG_INTERINDUSTRY_DATA_OBJECTS(0x7E);
const BerTag SCARD_TAG_DISPLAY_CONTROL(0x7F20);
const BerTag SCARD_TAG_CARDHOLDER_CERTIFICATE(0x7F21);
const BerTag SCARD_TAG_CARDHOLDER_REQUIREMENTS_INCLUDED_FEATURES(0x7F22);
const BerTag SCARD_TAG_CARDHOLDER_REQUIREMENTS_EXCLUDED_FEATURES(0x7F23);
const BerTag SCARD_TAG_BIOMETRIC_DATA_TEMPLATE(0x7F2E);
const BerTag SCARD_TAG_DIGITAL_SIGNATURE_BLOCK(0x7F3D);
const BerTag SCARD_TAG_CARDHOLDER_PRIVATE_KEY_TEMPLATE(0x7F48);
const BerTag SCARD_TAG_CARDHOLDER_PUBLIC_KEY_TEMPLATE(0x7F49);
const BerTag SCARD_TAG_CERTIFICATE_CONTENT_TEMPLATE(0x7F4E);
const BerTag SCARD_TAG_BIOMETRIC_INFORMATION_TEMPLATE(0x7F60);
const BerTag SCARD_TAG_BIOMETRIC_INFORMATION_GROUP_TEMPLATE(0x7F61);

class NSmartCardsDataElements
{
	N_DECLARE_STATIC_OBJECT_CLASS(NSmartCardsDataElements)
};

}}

#endif // !N_SMART_CARDS_DATA_ELEMENTS_HPP_INCLUDED
