'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
		Public Property AutoPlug() As Boolean
			Get
				Return (CBool(Me("AutoPlug")))
			End Get
			Set(ByVal value As Boolean)
				Me("AutoPlug") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("True")> _
		Public Property AutoUpdate() As Boolean
			Get
				Return (CBool(Me("AutoUpdate")))
			End Get
			Set(ByVal value As Boolean)
				Me("AutoUpdate") = value
			End Set
		End Property

		<Global.System.Configuration.UserScopedSettingAttribute(), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Configuration.DefaultSettingValueAttribute("Any")> _
		Public Property DeviceTypes() As Global.Neurotec.Devices.NDeviceType
			Get
				Return (CType(Me("DeviceTypes"), Global.Neurotec.Devices.NDeviceType))
			End Get
			Set(ByVal value As Global.Neurotec.Devices.NDeviceType)
				Me("DeviceTypes") = value
			End Set
		End Property
	End Class
End Namespace
