//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neurotec.Samples.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDirectory {
            get {
                return ((string)(this["LastDirectory"]));
            }
            set {
                this["LastDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Neurotec.Biometrics.Standards.ANValidationLevel NewValidationLevel {
            get {
                return ((global::Neurotec.Biometrics.Standards.ANValidationLevel)(this["NewValidationLevel"]));
            }
            set {
                this["NewValidationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public global::Neurotec.Biometrics.Standards.ANValidationLevel ValidationLevel {
            get {
                return ((global::Neurotec.Biometrics.Standards.ANValidationLevel)(this["ValidationLevel"]));
            }
            set {
                this["ValidationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewUseNistMinutiaNeighbors {
            get {
                return ((bool)(this["NewUseNistMinutiaNeighbors"]));
            }
            set {
                this["NewUseNistMinutiaNeighbors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseNistMinutiaNeighbors {
            get {
                return ((bool)(this["UseNistMinutiaNeighbors"]));
            }
            set {
                this["UseNistMinutiaNeighbors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NonStrictRead {
            get {
                return ((bool)(this["NonStrictRead"]));
            }
            set {
                this["NonStrictRead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergeDuplicateFields {
            get {
                return ((bool)(this["MergeDuplicateFields"]));
            }
            set {
                this["MergeDuplicateFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecoverFromBinaryData {
            get {
                return ((bool)(this["RecoverFromBinaryData"]));
            }
            set {
                this["RecoverFromBinaryData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeaveInvalidRecordsUnvalidated {
            get {
                return ((bool)(this["LeaveInvalidRecordsUnvalidated"]));
            }
            set {
                this["LeaveInvalidRecordsUnvalidated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastValidateDirectory {
            get {
                return ((string)(this["LastValidateDirectory"]));
            }
            set {
                this["LastValidateDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTwoDigitIdc {
            get {
                return ((bool)(this["UseTwoDigitIdc"]));
            }
            set {
                this["UseTwoDigitIdc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewUseTwoDigitIdc {
            get {
                return ((bool)(this["NewUseTwoDigitIdc"]));
            }
            set {
                this["NewUseTwoDigitIdc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTwoDigitFieldNumber {
            get {
                return ((bool)(this["UseTwoDigitFieldNumber"]));
            }
            set {
                this["UseTwoDigitFieldNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewUseTwoDigitFieldNumber {
            get {
                return ((bool)(this["NewUseTwoDigitFieldNumber"]));
            }
            set {
                this["NewUseTwoDigitFieldNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTwoDigitFieldNumberType1 {
            get {
                return ((bool)(this["UseTwoDigitFieldNumberType1"]));
            }
            set {
                this["UseTwoDigitFieldNumberType1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NewUseTwoDigitFieldNumberType1 {
            get {
                return ((bool)(this["NewUseTwoDigitFieldNumberType1"]));
            }
            set {
                this["NewUseTwoDigitFieldNumberType1"] = value;
            }
        }
    }
}
