'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8009
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property ConnectionType() As Integer
        Get
            Return CType(Me("ConnectionType"),Integer)
        End Get
        Set
            Me("ConnectionType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("localhost")>  _
    Public Property HostName() As String
        Get
            Return CType(Me("HostName"),String)
        End Get
        Set
            Me("HostName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("24932")>  _
    Public Property AdminPort() As Integer
        Get
            Return CType(Me("AdminPort"),Integer)
        End Get
        Set
            Me("AdminPort") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("25452")>  _
    Public Property ClientPort() As Integer
        Get
            Return CType(Me("ClientPort"),Integer)
        End Get
        Set
            Me("ClientPort") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1=What is your grandmother's name?;2=Where and when have you been born?;3=What is"& _ 
        " your favourite meal and drink?")>  _
    Public Property Phrases() As String
        Get
            Return CType(Me("Phrases"),String)
        End Get
        Set
            Me("Phrases") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FingerScanner() As String
        Get
            Return CType(Me("FingerScanner"),String)
        End Get
        Set
            Me("FingerScanner") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property IrisScanner() As String
        Get
            Return CType(Me("IrisScanner"),String)
        End Get
        Set
            Me("IrisScanner") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property PalmScanner() As String
        Get
            Return CType(Me("PalmScanner"),String)
        End Get
        Set
            Me("PalmScanner") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property VoiceCaptureDevice() As String
        Get
            Return CType(Me("VoiceCaptureDevice"),String)
        End Get
        Set
            Me("VoiceCaptureDevice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FaceCaptureDevice() As String
        Get
            Return CType(Me("FaceCaptureDevice"),String)
        End Get
        Set
            Me("FaceCaptureDevice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Fingers.DeterminePatternClass=True;Fingers.CalculateNfiq=True;Fingers.ReturnBinar"& _ 
        "izedImage=True;Faces.CreateThumbnailImage=True;Faces.DetectAllFeaturePoints=True"& _ 
        ";Faces.DetermineGender=True;Faces.DetermineAge=True;Faces.DetectProperties=True;"& _ 
        "Faces.RecognizeExpression=True;Faces.RecognizeEmotion=True;Palms.ReturnBinarized"& _ 
        "Image=True;Matching.WithDetails=True;Fingers.CheckForDuplicatesWhenCapturing=Tru"& _ 
        "e")>  _
    Public Property ClientProperties() As String
        Get
            Return CType(Me("ClientProperties"),String)
        End Get
        Set
            Me("ClientProperties") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property TableName() As String
        Get
            Return CType(Me("TableName"),String)
        End Get
        Set
            Me("TableName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property OdbcConnectionString() As String
        Get
            Return CType(Me("OdbcConnectionString"),String)
        End Get
        Set
            Me("OdbcConnectionString") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property FingersGeneralizationRecordCount() As Integer
        Get
            Return CType(Me("FingersGeneralizationRecordCount"),Integer)
        End Get
        Set
            Me("FingersGeneralizationRecordCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property FacesGeneralizationRecordCount() As Integer
        Get
            Return CType(Me("FacesGeneralizationRecordCount"),Integer)
        End Get
        Set
            Me("FacesGeneralizationRecordCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property PalmsGeneralizationRecordCount() As Integer
        Get
            Return CType(Me("PalmsGeneralizationRecordCount"),Integer)
        End Get
        Set
            Me("PalmsGeneralizationRecordCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
        "tring>Id IN (</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Id=</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Country=</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <"& _ 
        "string>City=</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>FirstName=</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>LastName=</strin"& _ 
        "g>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>YearOfBirth &gt;</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>GenderString='Male'</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>GenderString='Female'</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
    Public Property QueryAutoComplete() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("QueryAutoComplete"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("QueryAutoComplete") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property WarnHasSchema() As Boolean
        Get
            Return CType(Me("WarnHasSchema"),Boolean)
        End Get
        Set
            Me("WarnHasSchema") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
        "tring>Sample db schema#(FirstName string , LastName string , YearOfBirth int , G"& _ 
        "enderString string, Country string, City string)#(Thumbnail blob, EnrollData blo"& _ 
        "b)#Gender=GenderString#Thumbnail=Thumbnail#EnrollData=EnrollData</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <st"& _ 
        "ring>Remote server schema#(FirstName string , LastName string , YearOfBirth int "& _ 
        ", GenderString string, Country string, City string)##Gender=GenderString#Thumbna"& _ 
        "il=#EnrollData=</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
    Public Property Schemas() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("Schemas"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("Schemas") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property CurrentScema() As Integer
        Get
            Return CType(Me("CurrentScema"),Integer)
        End Get
        Set
            Me("CurrentScema") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
    Public Property LocalOperations() As Integer
        Get
            Return CType(Me("LocalOperations"),Integer)
        End Get
        Set
            Me("LocalOperations") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FacesMirrorHorizontally() As Boolean
        Get
            Return CType(Me("FacesMirrorHorizontally"),Boolean)
        End Get
        Set
            Me("FacesMirrorHorizontally") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Neurotec.Samples.Settings
            Get
                Return Global.Neurotec.Samples.Settings.Default
            End Get
        End Property
    End Module
End Namespace
